service: thierrybot

package:
  exclude:
    - node_modules/aws-sdk/**
    - docs/**

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
    ACTIVITY_LOG: ${self:service}-${opt:stage, self:provider.stage}-activity
    LOG_EVENT : ${self:service}-${opt:stage, self:provider.stage}-logNotice
    ORDER_EVENT : ${self:service}-${opt:stage, self:provider.stage}-orderNotice
    POSITION_EVENT : ${self:service}-${opt:stage, self:provider.stage}-positionNotice
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'sdb:GetAttributes'
        - 'sdb:PutAttributes'
      Resource: "arn:aws:sdb:${self:provider.region}:*:domain/${self:provider.environment.ACTIVITY_LOG}"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:

  sms:
    handler: functions/smsHandler.post
    memorySize: 128
    environment:
      LOG_EVENT : ${self:provider.environment.LOG_EVENT}
      ORDER_EVENT : ${self:provider.environment.ORDER_EVENT}
      POSITION_EVENT : ${self:provider.environment.POSITION_EVENT}
      TWILIO_AUTH_TOKEN : ${self:custom.secrets.TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER : ${self:custom.secrets.TWILIO_PHONE_NUMBER}
      ALERT_PHONE_NUMBER : ${self:custom.secrets.ALERT_PHONE_NUMBER}
      SERVICE_PHONE : ${self:custom.secrets.SERVICE_PHONE}
    events:
      - http:
          path: sms
          method: post
          cors: true

  log:
    handler: functions/logHandler.notify
    memorySize: 128
    environment:
      ACTIVITY_LOG : ${self:provider.environment.ACTIVITY_LOG}
      TWILIO_ACCOUNT_SID : ${self:custom.secrets.TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN : ${self:custom.secrets.TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER : ${self:custom.secrets.TWILIO_PHONE_NUMBER}
      ALERT_PHONE_NUMBER : ${self:custom.secrets.ALERT_PHONE_NUMBER}
    events:
      - sns: ${self:provider.environment.LOG_EVENT}
      - sns: ${self:provider.environment.ORDER_EVENT}
      - sns: ${self:provider.environment.POSITION_EVENT}

  order:
    handler: functions/orderHandler.notify
    memorySize: 128
    environment:
      LOG_EVENT : ${self:provider.environment.LOG_EVENT}
      IG_API_KEY: ${self:custom.secrets.IG_API_KEY}
      IG_USERNAME: ${self:custom.secrets.IG_USERNAME}
      IG_PASSWORD: ${self:custom.secrets.IG_PASSWORD}
      IG_HOST: ${self:custom.secrets.IG_HOST}
    events:
      - sns: ${self:provider.environment.ORDER_EVENT}

  position:
    handler: functions/positionHandler.notify
    memorySize: 128
    environment:
      LOG_EVENT : ${self:provider.environment.LOG_EVENT}
      IG_API_KEY: ${self:custom.secrets.IG_API_KEY}
      IG_USERNAME: ${self:custom.secrets.IG_USERNAME}
      IG_PASSWORD: ${self:custom.secrets.IG_PASSWORD}
      IG_HOST: ${self:custom.secrets.IG_HOST}
    events:
      - sns: ${self:provider.environment.POSITION_EVENT}
